# Generated by Django 4.0.2 on 2022-02-02 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_time', models.DateTimeField()),
                ('message', models.CharField(max_length=5000)),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.doctor')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.patient')),
            ],
        ),
    ]
